language: node_js

cache:
  directories:
    - node_module
    - ~/.npm

node_js:
  - '12'
git:
  depth: 3
script:
  - yarn test

notifications:
  slack: 
    secure: "KMcZuvSUtz6P5uHQtfZxjJRRVHB7YpkQElb+oVPl12iMKFtB8mqW9ualaNrNbitpTelPkwHqmt/hDOn8UbleI9cB/9lIgywKaQ1SfXbpgimq2t4L6vyskLdTf7aO4uIHn0YcXbUscbW+JNITiURF8rOU+VsocImSNIK4oFZr9DPd61zMX+eKdZCe7wk/sSoXK637xfZVj1qr/RH4i8CWVDKdplgaHNQFEoAqoZpWcRwTM50M+KiURqJMND1fEOrWfQN5xHSERc87HXJgxhoNZmL1Y+8igdPv2VYTWPZzSqXW/1be+s043qZyohaDJs5qzjPMMtUXM1yrrvtDSef0fS/X9HsxA0dcrzoAFSeJq5rymOlyylD3MsUtw+hVE8Ncd/o2fJ2/VU9ZMY1AqXQvGzX2vPrBtjY3gko/8XheSlDDKZqteK55FtytmruM//gWZyXpARZ0jgf7TvTmks7hB/NGTDtbaawF3CDYIQBbwEmODxeqFAVKPU2PmzUYE41mlOJjVqFo6CU+PZDxlN3DtbwTc0c63uDCkdHxt0EkZYx0j9cUPVxkqcSdE1tgG289wPX7l7RvuxeDxgRVrvm8FANPmARU7cuik1JIfZRSfEL8RWVNeUFsmI4Uxir1v5IFPv8Jt8Kh0p6TMn/QISBCZ6dHTSNKKEAqyXboibl9R10="
  email:
    recipiens:
      - fabiogomez28@gmail.com
    on_success: always
    on_failure: always
    
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0

deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: 
    secure: "Q+wLIzFWC95A7E9Z2se/2CGjHmLx8vF9oGtCzbGHqCik6l2VRvwQ2BbU5yhWJ/Q33N10FfZy9OejyGws2GvtFyZUwywEQLCQGu2vHJvSJYF9qXHMTzvWwaRJjSz/Vp96r1C+vl8+Jg5yAO8jIwNICeTrdQlHBmR0Lzl2ZM2zLAcfyZ95NXZP7WA98eBbwapuERvN7yKPfetBeMofQZidSxd7IwlffQK4GOi6w1Np2vjCMcI3ELuwkzZ1zpxX23jIJc0Upq8TOzYaHq19sIBeT8LERnfYdyBi7xfqc+O2681wuOsMNlyaAp3O6MRRzdDDwpSINyzMzb/aSMiO5PoobsWhY9ec9zeOhd7sfKF0Xj/nyNbdpd5Yd9d6vaY8eweFH4YLx0xdUKdorWFsWU8L8cBZpE3QcXayz2ZKg5WxAJv6FWAxxF7TqPxG46HtvSt1roeV7BStxJyNmDPVQUNEKor5fl90gQKJuAxeQUGrOoEUKmfNg74mQ5DBPaRANGwOgsKXHpETJDBC6IxnoSDHU5XseAxEqa2UeGmcSAoSz0lw40BjXCCAx3SCGiTrhswKToQqGVarjb+1rrhPASGz2fdit8WQGS1az8ghUW0CSLP4sBCqxdmh3aZ58SiEpbiQIqEBlQySSuGrT0z3S759kD6KsHEfMuqICD8uGMUhR0w="
  app: platzi-store-personal
  on:
    repo: fabiogomez/platzi-store-backend